// <auto-generated />
namespace Egreeting.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class initdb : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initdb));
        
        string IMigrationMetadata.Id
        {
            get { return "201910191644166_init-db"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
